hr-mitra/config/routes.rb
Rails.application.routes.draw do
  # Uncomment the following lines if you want to use the default routes
  # get 'home/index'
  # get '/home' => 'home#index'

  root 'home#index'
  
  resources :employees do
    collection do
      get :export_csv
    end
  end
  
  resources :documents
  
  # Define routes for custom pages
  get '/about-us' => 'pages#about_us'
  get '/contact-us' => 'pages#contact_us'
  get '/privacy-policy' => 'pages#privacy_policy'
  get '/terms-and-conditions' => 'pages#terms_and_conditions'
end

hr-mitra/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

hr-mitra/app/models/document.rb
class Document < ApplicationRecord
  belongs_to :employee
end

hr-mitra/app/models/employee.rb
class Employee < ApplicationRecord
  has_many :document
  validates :first_name, :last_name, presence: true
  validates :personal_email, presence: true, uniqueness: true
  validates :city, :state, :country, :pincode, :address_line_1, presence: true

  def name
    "#{first_name.capitalize} #{last_name.capitalize}".strip
  end

  def full_address
    "#{address_line_1.capitalize},#{address_line_2.capitalize} #{city.capitalize} ,#{state.capitalize}, #{country.capitalize}, Pincode - #{pincode.capitalize}"
  end
end

hr-mitra/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

hr-mitra/app/controllers/documents_controller.rb
class DocumentsController <ApplicationController
	class EmployeesController < ApplicationController
  before_action :set_employee, only: [:edit, :update, :destroy, :show]

  def index
    @documents = Dcument.all
  end

  def new
   @document = Document.new
  end

  def create
   @document = Document.new(document_params)
    if @employee.save
      redirect_to employees_path, notice: 'Employee has been successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @employee.update(document_params)
      flash[:success] = 'Employee has been updated successfully'
      redirect_to employees_path
    else
      render :edit
    end
  end

  def destroy
    if @employee.destroy
      redirect_to employees_path, notice: 'Employee has been successfully deleted.'
    else
      redirect_to employees_path, alert: 'There was an error deleting the employee.'
    end
  end

  def show
  end

  private

  def document_params
    params.require(:employee).permit(:first_name, :middle_name, :last_name, :personal_email, :city, :state, :country, :pincode, :address_line_1, :address_line_2)
  end

  def set_employee
   @document = Document.find(params[:id])
  rescue ActiveRecord::RecordNotFound => error
    redirect_to employees_path, alert: 'Employee not found'
  end
end

end

hr-mitra/app/controllers/employees_controller.rb
# app/controllers/employees_controller.rb

require 'csv'

class EmployeesController < ApplicationController
  before_action :set_employee, only: [:edit, :update, :destroy, :show]

  def index
    @employees = Employee.all

    respond_to do |format|
      format.html
      format.csv { send_data export_csv(@employees), filename: "employees-#{Date.today}.csv" }
    end
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      redirect_to employees_path, notice: 'Employee has been successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @employee.update(employee_params)
      flash[:success] = 'Employee has been updated successfully'
      redirect_to employees_path
    else
      render :edit
    end
  end

  def destroy
    if @employee.destroy
      redirect_to employees_path, notice: 'Employee has been successfully deleted.'
    else
      redirect_to employees_path, alert: 'There was an error deleting the employee.'
    end
  end

  def show
  end

  private

  def employee_params
    params.require(:employee).permit(:first_name, :middle_name, :last_name, :personal_email, :city, :state, :country, :pincode, :address_line_1, :address_line_2)
  end

  def set_employee
    @employee = Employee.find(params[:id])
  rescue ActiveRecord::RecordNotFound => error
    redirect_to employees_path, alert: 'Employee not found'
  end

  def export_csv(employees)
    CSV.generate(headers: true) do |csv|
      csv << ["First Name", "Middle Name", "Last Name", "Email", "City", "State", "Country", "Pincode", "Address Line 1", "Address Line 2"]
      employees.each do |employee|
        csv << [employee.first_name, employee.middle_name, employee.last_name, employee.personal_email, employee.city, employee.state, employee.country, employee.pincode, employee.address_line_1, employee.address_line_2]
      end
    end
  end
end

hr-mitra/app/controllers/home_controller.rb
class HomeController<ApplicationController
    def index
    end
end 

hr-mitra/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about_us
  end

  def contact_us
  end

  def privacy_policy
  end

  def terms_and_conditions
  end
end

hr-mitra/app/helpers/application_helper.rb
module ApplicationHelper
end

hr-mitra/app/helpers/pages_helper.rb
module PagesHelper
end

hr-mitra/app/views/employees/_form.html.erb
<%= form_with model: @employee do |form| %>
<div class="row">
 <!-- Displaying all error message  -->
        <!-- 	<%# if @employee.errors.any? %>
        	<div class="col-lg-12">
        		<p class="lead">Please fix error below</p>
        		<#% #@employee.errors.full_messages.each do |message| %>
        		<p class="text-danger"> <#%= message %></p>
        		<#% end -%>
        	</div>
        	<%# end -%> -->


        <div class="col-lg-4">
          <div class="form-group">
            <span style="font-weight: bold;"><%= form.label :first_name, class: "mb-2" %></span>
            <%= form.text_field :first_name, class: "form-control form-control-lg rounded-0", pattern: "[^0-9]*" %>
            <% @employee.errors.full_messages_for(:first_name).each do |message| %>
            <p class="text-danger"> <%= message %></p>
            <% end -%>
            <% if @employee.errors[:first_name].any? %>
            <% @employee.errors[:first_name].each do |error| %>
            <% if error == "can't be blank" %>
            <p class="text-danger">First name is required*</p>
            <% end %>
            <% end %>
            <% end %>
          </div>
        </div>


        <div class="col-lg-4">
          <div class="form-group">
            <span style="font-weight: bold;"><%= form.label :middle_name, class: "mb-2" %></span>
            <%= form.text_field :middle_name, class: "form-control form-control-lg rounded-0" %>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="form-group">
            <span style="font-weight: bold;"><%= form.label :last_name, class: "mb-2" %></span>
            <%= form.text_field :last_name, class: "form-control form-control-lg rounded-0" %>
            <% if @employee.errors[:last_name].any? %>
            <% @employee.errors[:last_name].each do |error| %>
            <% if error == "can't be blank" %>
            <p class="text-danger">Last name is required*</p>
            <% end %>
            <% end %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-4">
          <div class="form-group">
            <span style="font-weight: bold;"><%= form.label :personal_email, class: "mb-2" %></span>
            <%= form.text_field :personal_email, class: "form-control form-control-lg rounded-0" %>
            <% if @employee.errors[:personal_email].any? %>
            <% @employee.errors[:personal_email].each do |error| %>
            <% if error == "can't be blank" %>
            <p class="text-danger">Email is required*</p>
            <% end %>
            <% end %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-6">
          <div class="form-group">
            <span style="font-weight: bold;"><%= form.label :address_line_1, class: "mb-2" %></span>
            <%= form.text_field :address_line_1, class: "form-control form-control-lg rounded-0" %>
          </div>
        </div>
        <div class="col-lg-6">
          <div class="form-group">
            <span style="font-weight: bold;"><%= form.label :address_line_2, class: "mb-2" %></span>
            <%= form.text_field :address_line_2, class: "form-control form-control-lg rounded-0" %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-3">
          <div class="form-group">
            <span style="font-weight: bold;"><%= form.label :city, class: "mb-2" %></span>
            <%= form.text_field :city, class: "form-control form-control-lg rounded-0" %>
            <% if @employee.errors[:city].any? %>
            <% @employee.errors[:city].each do |error| %>
            <% if error == "can't be blank" %>
            <p class="text-danger">City is required*</p>
            <% end %>
            <% end %>
            <% end %>
          </div>
        </div>
        <div class="col-lg-3">
          <div class="form-group">
            <%= form.label :state, class: "mb-2 font-weight-bold" %>
            <%= form.select :state, options_for_select([
              ['Andhra Pradesh', 'AP'],
              ['Arunachal Pradesh', 'AR'],
              ['Assam', 'AS'],
              ['Bihar', 'BR'],
              ['Chhattisgarh', 'CT'],
              ['Gujarat', 'GA'],
              ['Haryana', 'HR'],
              ['Himachal Pradesh', 'HP'],
              ['Jammu and Kashmir', 'JK'],
              ['Goa', 'GA'],
              ['Jharkhand', 'JH'],
              ['Karnataka', 'KA'],
              ['Kerala', 'KL'],
              ['Madhya Pradesh', 'MP'],
              ['Maharashtra', 'MH'],
              ['Manipur', 'MN'],
              ['Meghalaya', 'ML'],
              ['Mizoram', 'MZ'],
              ['Nagaland', 'NL'],
              ['Odisha', 'OR'],
              ['Punjab', 'PB'],
              ['Rajasthan', 'RJ'],
              ['Sikkim', 'SK'],
              ['Tamil Nadu', 'TN'],
              ['Telangana', 'TG'],
              ['Tripura', 'TR'],
              ['Uttarakhand', 'UT'],
              ['Uttar Pradesh', 'UP'],
              ['West Bengal', 'WB'],
              ['Andaman and Nicobar Islands', 'AN'],
              ['Chandigarh', 'CH'],
              ['Dadra and Nagar Haveli', 'DN'],
              ['Daman and Diu', 'DD'],
              ['Delhi', 'DL'],
              ['Lakshadweep', 'LD'],
              ['Puducherry', 'PY']
              ], @employee.state), { include_blank: 'Select State' }, class: "form-control form-control-lg rounded-0" %>
              <% if @employee.errors[:state].any? %>
              <p class="text-danger"><%= @employee.errors[:state].first %></p>
              <% end %>
            </div>
          </div>
          <div class="col-lg-3">
            <div class="form-group">
              <span style="font-weight: bold;"><%= form.label :country, class: "mb-2" %></span>
              <%= form.text_field :country, class: "form-control form-control-lg rounded-0" %>
              <% if @employee.errors[:country].any? %>
              <% @employee.errors[:country].each do |error| %>
              <% if error == "can't be blank" %>
              <p class="text-danger">Country  is required*</p>
              <% end %>
              <% end %>
              <% end %>
            </div>
          </div>
          <div class="col-lg-3">
            <div class="form-group">
              <span style="font-weight: bold;"><%= form.label :pincode, class: "mb-2" %></span>
              <%= form.text_field :pincode, class: "form-control form-control-lg rounded-0" %>
              <% if @employee.errors[:pincode].any? %>
              <% @employee.errors[:pincode].each do |error| %>
              <% if error == "can't be blank" %>
              <p class="text-danger">Pincode  is required*</p>
              <% end %>
              <% end %>
              <% end %>
            </div>
          </div>
        </div>
        <div class="row">
         <div class ="col-lg-12 mt-4">
           <%= form.submit class: "btn btn-primary btn-lg rounded-0", type: "submit" %>
           <%= link_to "Back to Employee",employees_path, class: "btn btn-primary btn-lg rounded-0", type: "submit" %>
         </div>
       </div>
       <% end %>

hr-mitra/app/views/employees/edit.html.erb
<div class="col-lg-12">
  <div class="card rounded-0 mt-5 mb-5">
    <div class="card-body">
      <h2 class="text-center">Edit Registration</h2>
    </div>
  </div>
  <!-- Instantiating the model controller -->
  <div class="card rounded-0">
    <div class="card-body">
      <%= render 'form' , employee: @employee%>
    </div>
  </div>
</div>

hr-mitra/app/views/employees/index.html.erb
<!-- app/views/employees/index.html.erb -->

<div class="col-lg-12">
  <% if flash[:success] %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <%= flash[:success] %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
  <% if flash[:notice] %>
    <div class="alert alert-success alert-dismissible fade show " role="alert">
      <%= flash[:notice] %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
  <% if flash[:alert] %>
    <div class="alert alert-danger alert-dismissible fade show " role="alert">
      <%= flash[:alert] %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
  
  <div class="card rounded-0 mt-5 mb-5">
    <div class="card-body">
      <h2 class="text-center">Listing Employees</h2>
    </div>
  </div>
  
  <%= link_to "Create New Employee", new_employee_path, class: "btn btn-primary btn-lg mb-4 rounded-0" %>
  <%= link_to "Export to CSV", employees_path(format: :csv), class: "btn btn-secondary btn-lg mb-4 rounded-0" %>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Full Name</th>
        <th>Email</th>
        <th>Address</th>
        <th colspan="3" class="text-center">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @employees.each do |employee| %>
        <tr>
          <td><%= employee.first_name + " " + employee.last_name %></td>
          <td><%= employee.personal_email %></td>
          <td><%= employee.full_address %></td>
          <th><%= link_to "Edit", edit_employee_path(employee), class: "btn btn-warning btn-lg mb-4 rounded-0" %></th>
          <th><%= link_to "View", employee_path(employee), class: "btn btn-warning btn-lg mb-4 rounded-0" %></th>
          <th><%= link_to "Delete", employee_path(employee), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-lg mb-4 rounded-0" %></th>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

hr-mitra/app/views/employees/new.html.erb
<div class="col-lg-12">
	<div class="card rounded-0 mt-5 mb-5">
		<div class="card-body">
			<h2 class="text-center">Employee Registration</h2>
		</div>
	</div>

	<div class="card rounded-0">
		<div class="card-body">
			<%= render 'form' , employee: @employee%>
		</div>
	</div>
</div>

hr-mitra/app/views/employees/show.html.erb
<div class="col-lg-12">
  <div class="card" style="border: 1px solid #e3e6f0; border-radius: .35rem; box-shadow: 0 0 15px rgba(0, 0, 0, 0.1); margin-top: 3rem; margin-bottom: 3rem;">
    <div class="card-body" style="padding: 2rem;">
      <h2 class="text-center" style="text-align: center;">Employee Details</h2>
      <div class="row mt-5" style="margin-left: 15rem;">
        <div class="col-lg-6">
          <h3>Personal Information</h3>
          <img
          src="https://mdbootstrap.com/img/new/avatars/8.jpg"
          alt=""
          style="width: 45px; height: 45px"
          class="rounded-circle"
          />
          <p class="lead" style="font-size: 1.25rem; font-weight: 300;"><strong>First Name: </strong><%= @employee.first_name %></p>
          <p class="lead" style="font-size: 1.25rem; font-weight: 300;"><strong>Middle Name: </strong><%= @employee.middle_name.present? ? @employee.middle_name: 'NA' %></p>
          <p class="lead" style="font-size: 1.25rem; font-weight: 300;"><strong>Last Name: </strong><%= @employee.last_name %></p>
          <p class="lead" style="font-size: 1.25rem; font-weight: 300;"><strong>Personal Email: </strong><%= @employee.personal_email %></p>
          <%= link_to "Back to Employee",employees_path, class: "btn btn-primary btn-lg rounded-0", type: "submit" %>	
          <%= link_to "Edit Employee", edit_employee_path(@employee), class: "btn btn-warning btn-lg  rounded-0" %>
        </div>
        <div class="col-lg-6">
          <h3>Address Information</h3>
          <p class="lead" style="font-size: 1.25rem; font-weight: 300;"><strong>Address Line 1: </strong><%= @employee.address_line_1 %></p>
          <p class="lead" style="font-size: 1.25rem; font-weight: 300;"><strong>Address Line 2: </strong><%= @employee.address_line_2 %></p>
          <p class="lead" style="font-size: 1.25rem; font-weight: 300;"><strong>City: </strong><%= @employee.city %></p>
          <p class="lead" style="font-size: 1.25rem; font-weight: 300;"><strong>State: </strong><%= @employee.state %></p>
          <p class="lead" style="font-size: 1.25rem; font-weight: 300;"><strong>Country: </strong><%= @employee.country %></p>
          <p class="lead" style="font-size: 1.25rem; font-weight: 300;"><strong>Pincode: </strong><%= @employee.pincode %></p>
        </div>
      </div>
    </div>
  </div>
</div>
<%# <table class="table align-middle mb-0 bg-white">
  <thead class="bg-light">
    <tr>
      <th colspan="3" class="text-center">Employee Details</th>
    </tr>
     <tr>
      <th>Employee Details</th>
      <th>Employee Details</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <div class="d-flex align-items-center">
          <img
              src="https://mdbootstrap.com/img/new/avatars/8.jpg"
              alt=""
              style="width: 45px; height: 45px"
              class="rounded-circle"
              />
          <div class="ms-3">
            <p class="fw-bold mb-1">First Name : John Doe</p>
            <p class="text-muted mb-0">Middle Name :NA</p> 
            <p class="text-muted mb-0">Last Name :NA</p> 
            <p class="text-muted mb-0">Personal Email : john.doe@gmail.com</p>
          </div>
        </div>
      </td>
      <td>
        <p class="fw-normal mb-1">Address Line 1: ward no 05</p>
        <p class="text-muted mb-0">Address Line 2: silpur </p>
        <p class="fw-normal mb-1">City: Kotma 01</p>
        <p class="text-muted mb-0">State: MP</p>
        <p class="fw-normal mb-1">Country: india</p>
        <p class="text-muted mb-0">Pincode: 484334</p>
      </td>
    </tr>
  </tbody>
</table> %>

hr-mitra/app/views/home/index.html.erb
<center><h1>WELCOME RUBY</h1></center>
<%= render 'shared/links'%>

hr-mitra/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HrMitra</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'shared/header'%>
  <div class="container">
    <div class="row">
    <%= yield %>
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <%= render 'shared/footer'%>
  </body>
</html>

hr-mitra/app/views/pages/about_us.html.erb
<%= render 'shared/links'%>

hr-mitra/app/views/pages/contact_us.html.erb
<%= render 'shared/links'%>

hr-mitra/app/views/pages/privacy_policy.html.erb
<%= render 'shared/links'%>

hr-mitra/app/views/pages/terms_and_conditions.html.erb
<%= render 'shared/links'%>

hr-mitra/app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="text-center text-lg-start bg-body-tertiary text-muted">
  <!-- Section: Social media -->
  <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
    <!-- Left -->
    <div class="me-5 d-none d-lg-block">
      <span>Get connected with us on social networks:</span>
    </div>
    <!-- Left -->

    <!-- Right -->
    <div>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-facebook-f"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-twitter"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-google"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-instagram"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-linkedin"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-github"></i>
      </a>
    </div>
    <!-- Right -->
  </section>
  <!-- Section: Social media -->

  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3"></i>Company name
          </h6>
          <p>
            Here you can use rows and columns to organize your footer content. Lorem ipsum
            dolor sit amet, consectetur adipisicing elit.
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Products
          </h6>
          <p>
            <a href="#!" class="text-reset">Angular</a>
          </p>
          <p>
            <a href="#!" class="text-reset">React</a>
          </p>
        
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Useful links
          </h6>
          <p>
            <a href="#!" class="text-reset">Pricing</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Settings</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
          <p><i class="fas fa-home me-3"></i> New York, NY 10012, US</p>
          <p>
            <i class="fas fa-envelope me-3"></i>
            Hr-mitra@example.com
          </p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2021 Copyright:
    <a class="text-reset fw-bold" href="#">www.Hr-mitra.com</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->

hr-mitra/app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg bg-primary bg-body-primary" >
  <div class="container-fluid"><%= link_to 'Hr-Mitra', root_path, class: "navbar-brand", target: '_blank', style: 'color: red; font-weight: bold;' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <label><%= link_to 'Home', root_path, target: '_blank', style: 'color: red; '%></label>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

hr-mitra/app/views/shared/_links.html.erb
<%# link_to 'About us', controller: :pages, action: :about_us %>
<%# link_to 'About us', '/about_us' %>
<%= link_to 'About us', about_us_path, target: '_blank', style: 'color: red;' %>
<%= link_to 'Contact Us', contact_us_path, target: '_blank', style: 'color: red;' %>
<%= link_to 'Privacy Policy', privacy_policy_path, target: '_blank', style: 'color: red;' %>
<%= link_to 'T&C', terms_and_conditions_path, target: '_blank', style: 'color: red;' %>